[platformio]
src_dir = src
default_envs = example_read_hz_esp32s3, example_read_hz_atoms3, example_read_hz_nano_every,  example_rotate_esp32s3, example_rotate_atoms3, example_rotate_nano_every, example_read_angle_esp32s3, example_read_angle_atoms3, example_read_parameters_atoms3

[env]
framework = arduino
test_build_project_src = yes
monitor_speed = 115200

[env:nano_every]
platform = atmelmegaavr
board = nano_every

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
build_flags =
    -D EN_PIN=-1
    -D RX_PIN=18
    -D TX_PIN=17

[env:atoms3]
platform = espressif32
board = m5stack-atoms3
build_flags =
    -D EN_PIN=6
    -D RX_PIN=5
    -D TX_PIN=38

[env:example_read_hz_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
build_src_filter = +<../examples/read_hz.cpp> +<*.cpp>
build_flags =
    -D EN_PIN=-1
    -D RX_PIN=18
    -D TX_PIN=17

[env:example_read_hz_atoms3]
platform = espressif32
board = m5stack-atoms3
build_src_filter = +<../examples/read_hz.cpp> +<*.cpp>
build_flags =
    -D EN_PIN=6
    -D RX_PIN=5
    -D TX_PIN=38

[env:example_read_hz_nano_every]
platform = atmelmegaavr
board = nano_every
build_src_filter = +<../examples/read_hz.cpp> +<*.cpp>

[env:example_rotate_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
build_src_filter = +<../examples/rotate.cpp> +<*.cpp>
build_flags =
    -D EN_PIN=-1
    -D RX_PIN=18
    -D TX_PIN=17

[env:example_rotate_atoms3]
platform = espressif32
board = m5stack-atoms3
build_src_filter = +<../examples/rotate.cpp> +<*.cpp>
build_flags =
    -D EN_PIN=6
    -D RX_PIN=5
    -D TX_PIN=38

[env:example_rotate_nano_every]
platform = atmelmegaavr
board = nano_every
build_src_filter = +<../examples/rotate.cpp> +<*.cpp>

[env:example_read_angle_atoms3]
platform = espressif32
board = m5stack-atoms3
build_src_filter = +<../examples/read_angle.cpp> +<*.cpp>
build_flags =
    -D EN_PIN=6
    -D RX_PIN=5
    -D TX_PIN=38
lib_deps =
    https://github.com/fredlarochelle/RunningStats

[env:example_read_angle_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
build_src_filter = +<../examples/read_angle.cpp> +<*.cpp>
build_flags =
    -D EN_PIN=-1
    -D RX_PIN=18
    -D TX_PIN=17
lib_deps =
    https://github.com/fredlarochelle/RunningStats

[env:example_read_parameters_atoms3]
platform = espressif32
board = m5stack-atoms3
build_src_filter = +<../examples/read_parameters.cpp> +<*.cpp>
build_flags =
    -D EN_PIN=6
    -D RX_PIN=5
    -D TX_PIN=38

[env:nejineji_hand]
platform = espressif32
board = m5stack-atoms3
build_src_filter = +<../examples/nejineji_hand.cpp> +<*.cpp>
build_flags =
    -D EN_PIN=6
    -D RX_PIN=5
    -D TX_PIN=38
lib_deps =
    https://github.com/fredlarochelle/RunningStats
    m5stack/M5AtomS3 @ 1.0.0
    m5stack/M5Unified @ 0.1.14
    Fastled/FastLED @ 3.6.0
    mathertel/OneButton